# Generated by Django 3.2.6 on 2021-10-03 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('userinfo', models.CharField(max_length=512)),
                ('useremail', models.CharField(max_length=64)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpic', models.ImageField(upload_to='userpic/%Y%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png', 'bmp', 'webp'], message='文件类型不对')])),
                ('pic_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASEAPP.user')),
            ],
            options={
                'db_table': 'UserPic',
            },
        ),
    ]
