# Generated by Django 3.2.6 on 2021-10-03 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASEAPP', '0002_alter_userpic_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpic',
            name='userpic',
            field=models.ImageField(upload_to='userpic/%Y%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png', 'bmp', 'webp'], message='文件类型不对')]),
        ),
    ]
