# Generated by Django 3.2.6 on 2021-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASEAPP', '0003_alter_userpic_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpic',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
