# Generated by Django 3.2.6 on 2021-10-03 15:18

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BASEAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', mdeditor.fields.MDTextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASEAPP.user')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('comment_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.bolg')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASEAPP.user')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
