# Generated by Django 3.2.6 on 2021-10-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolg',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
