# Generated by Django 3.2.6 on 2021-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_bolg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolg',
            name='date',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
