# Generated by Django 3.2.6 on 2021-10-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0005_alter_bolg_date'),
        ('BASEAPP', '0003_alter_userpic_userpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('channel_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.bolg')),
                ('channel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASEAPP.user')),
            ],
            options={
                'db_table': 'Channel',
            },
        ),
    ]
