# Generated by Django 3.2.6 on 2021-10-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
