# Generated by Django 3.2.6 on 2021-10-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_bolg_date'),
        ('BASEAPP', '0004_userpic_is_delete'),
        ('Channel', '0003_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.bolg'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BASEAPP.user'),
        ),
    ]
